### ISSUE TITLE
add Golden Hand quest for new skill level up book

### ISSUE THREAD

**Issue by Lapahn** [HeartofPhos/exile-leveling#100]
We now get Golden Hand as a quest that gives a Skill Book and the current route doesn't seem to have that updated yet.

Please add it if you can, thanks! :)

**Comment by sebsebmc** [comment]
I see it here 
![image](https://github.com/user-attachments/assets/e6f7ffa4-eb94-4027-bff9-ecb53427578a)

**Comment by HeartofPhos** [comment]
You may need to hard refresh the page with Ctrl-F5 to get latest version, but it has been added
