### ISSUE TITLE
[Feature] Create a PWA

### ISSUE THREAD

**Issue by LudgerPeters** [HeartofPhos/exile-leveling#16]
Hey, small improvement is to look at create a PWA version, that would allow you to install it as an app in most modern browsers: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

**Comment by Halkreen** [comment]
Hi, was thinking the same thing. I might have some time to create a PR on this, I was thinking of make it optional by default to avoid bad side effects.
