### ISSUE TITLE
Not an issue - POE client.txt integration

### ISSUE THREAD

**Issue by Lokkedian** [HeartofPhos/exile-leveling#20]
This post isn't an issue, but have you thought about either a browser extension or a standalone executable that can read the client.txt log file and update itself? No easy task, but would be neat.

**Comment by HeartofPhos** [comment]
Currently not planned but you can use [LLK-UI Leveling-Tracker](https://github.com/Lailloken/Lailloken-UI/wiki/Leveling-Tracker) which overlays the route as well as handles some transitions based on the `client.txt`

**Comment by Lokkedian** [comment]
Amazing! Thank you.
