### ISSUE TITLE
Feature Request: Option to remove tasks entirely (not just gray out)

### ISSUE THREAD

**Issue by mrobert09** [HeartofPhos/exile-leveling#24]
This is a great step-by-step guide for people who need it, but for people who are already familiar with the campaign, it could be helpful to remove a lot of the already-known stuff from the task list. For example, I am mostly just looking for a reminder of when and where to buy gems (and maybe also a reminder of which quests are skillpoints and which aren't). At the moment it is a bit of a pain because even if I disable stuff I don't want beforehand I need to do a lot of scrolling to see what my next reminder is.

**Comment by HeartofPhos** [comment]
#32 Adds basic route editing functionality, you can use this to fully remove tasks you don't care about and will persist between sessions
