### ISSUE TITLE
"Waypoint → Location" display names should display the name of the World Location and Act number (if switching acts)

### ISSUE THREAD

**Issue by Meigs2** [HeartofPhos/exile-leveling#34]
Hi! Once again, amazing tool, I've leveled 3 character's this league so far using Exile-Level and it's been the one thing keeping me around this league, so thanks again.

One suggestion that I think would help people who aren't super familiar with maps and the order of progression is having the display name of the location for "Waypoint → Location" steps to show the *world* location name in the step, not the name of the map as it appears in the top right. It was confusing for me when in Act 1 it instructs you to go to The Cavern of Wrath, but the location is actually Merveil's Cavern, as it appears on the map. This confused me the first time around, but once you know you wont really forget again.

Also, when backtracking, like in Act 7 when you are instructed to back-track to Act 6, there is no indication that you need to go to the previous act, you just need to remember. Having a greyed-out "(Act 6)" when you need to waypoint between acts would make it much more clear where you need to wp to.

Thanks!

**Comment by HeartofPhos** [comment]
Interesting I never noticed map waypoints could have different names from the actual instances, currently that info is all datamined so I'll have to look into hooking it up, but seems doable

Greyed out text when navigating between acts is a great idea, will look into it as well.
