### ISSUE TITLE
Add a "League Start"/"2nd+ Character" setting to skip steps for things like ascendancies, crafting options, and The Library

### ISSUE THREAD

**Issue by Meigs2** [HeartofPhos/exile-leveling#35]
Hi!

While leveling my second and third characters using Exile Leveling, one thing I had to keep track of (and ignore) were the steps to unlock labs, crafting recipes, and The Library/Siosa. I think there's at least one or two areas that we travel to just to unlock the trial of ascendancies, and those aren't needed when leveling a second character. Because of this, I have to scroll down and double check that the part I'm on isn't exclusively for unlocking trials, as otherwise I can skip that part. Same with Siosa, if you're leveling a second character you'd have access to Lilly Roth to buy your gems in your hideout. This is less important, but all the crafting recipe unlock steps can clutter the progression if you already have them.

My suggestion would be to have a setting for "League Start"/"2nd+ Character" to enable/disable anything that's not purely to level. When first loading Exile Leveling, instead of starting on the current route, a modal dialog would appear welcoming you to Exile Leveling, shows some info about the site, and asks if you would like to start your route for "League Start", explaining that if this is your first character on the league where you have not unlocked your crafts, or have not completed your trials, you should choose this option, and if this is your second character or you are a veteran who just wants the route, use the "2nd+ Character" route as it skips the unlocks you already should have. You'd be about to check/uncheck a setting to show/hide those steps whenever you want, if you made a mistake for example.

When clicking "Reset Progress", this dialog would appear again. I'm assuming the site's cookies/local storage is cleared when this happens so this would just be built in behavior.

This would be a good spot to have some basic info about Exile Leveling, link to the GitHub, explaining features, patch notes, etc. This component could simply be a separate "About Exile Leveling" that would replace the "Project on GitHub" button that exists currently.

**Comment by HeartofPhos** [comment]
This is actually already a feature and can be toggled on the build page
![image](https://user-images.githubusercontent.com/43216176/214173750-00824b30-3cb3-4b7e-a58a-c8bd1135a3c6.png)
Currently crafting recipes aren't explicitly excluded though (unless they're in a Trial)

Though some basic info/features page would go a long way as the feature set grows

**Comment by Meigs2** [comment]
Well... I should have done my due diligence. Thanks.

I'd still suggest some sort of initial splash screen to have these options visible right at the start, maybe an prompt to import a pob right then and there. Would let people know these options exist before they start using the tool, especially if they've never used Exile Leveling before.

Either way, thanks.
