### ISSUE TITLE
Can't import leveling guide in Lailloken-UI

### ISSUE THREAD

**Issue by Adrianos123** [HeartofPhos/exile-leveling#38]
I cannot import in Lailloken-UI anymore. Even without any build, the "standard" version, it's not working. When I try to import it says "invalid import data". My friend tried as well and he is receiving the same message. Can you please help me? Thank you!

**Comment by HeartofPhos** [comment]
There's a pre-release fix you can use here https://github.com/Lailloken/Lailloken-UI/issues/186 while updates are in progress

**Comment by HeartofPhos** [comment]
Fixed by https://github.com/Lailloken/Lailloken-UI/pull/187
