### ISSUE TITLE
Add NPC name to quest hand in.

### ISSUE THREAD

**Issue by blahblahdrugs** [HeartofPhos/exile-leveling#44]
Talk to {generic|Tarkleigh}, hand in {quest|a1q1} #Enemy at the Gate

**Comment by HeartofPhos** [comment]
I'm interested in doing this if it's possible to populate with data mining, some initial investigation shows that `Data/QuestAchievements.dat64` might have the data required to link NPC to a given quest.

**Comment by HeartofPhos** [comment]
Resolved by 72d613f1555cd6fd4b94c4a2e095d7615c9d0fca

**Comment by blahblahdrugs** [comment]
Looks great!
