### ISSUE TITLE
pobb.in raw API

### ISSUE THREAD

**Issue by Dav1dde** [HeartofPhos/exile-leveling#49]
Can you switch the following API endpoint to [use the `/raw` suffix](https://github.com/Dav1dde/pasteofexile#public-api)?

https://github.com/HeartofPhos/exile-leveling/blob/b040968e5694fe11692b07d73c49ab7087c781ce/web/src/components/BuildImportForm/pob.ts#L174-L177

And if it's not too much trouble add/override the `User-Agent` for your CORS proxy?

https://github.com/HeartofPhos/exile-leveling/blob/b040968e5694fe11692b07d73c49ab7087c781ce/web/src/components/BuildImportForm/pob.ts#L193

While the PoB API works, these requests do mess with my monitoring and the it is only supposed to be used by PoB.

Thanks!

**Comment by HeartofPhos** [comment]
Updated the URL and added User-Agent to the request, let me know if there's anything else you'd like adjusted

**Comment by Dav1dde** [comment]
@HeartofPhos awesome thanks!
