### ISSUE TITLE
Skill tree is blank in safari on ios

### ISSUE THREAD

**Issue by Wibbbs** [HeartofPhos/exile-leveling#51]
When importing a build the skill tree is blank on iOS in safari.

![DB11E723-8DBF-4431-B148-8A950ED6C4FC](https://user-images.githubusercontent.com/24574428/229773714-f8d33451-7e78-438b-b63d-626a1238dcc7.png)

**Comment by Wibbbs** [comment]
Just a little more info. I tried on an iPhone on iOS 16.3 and 16.4, and also an iPad on iOS beta 16.5. All had the same issue.

**Comment by HeartofPhos** [comment]
Do you know if the issue occurs on MacOS Safari as well or is it limited to iOS platforms? Don't have a device to test with myself so will need some additional investigation

**Comment by StojHalina** [comment]
I can confirm it doesn't work on iPad iOS in both Chrome and Safari, although on my android phone in Chrome it works as intended.

**Comment by Wibbbs** [comment]
I unfortunately don't have a mac to try safari on there. I dont have much time but if I can find some I will try to fork the repo and see if I can poke around.

**Comment by HeartofPhos** [comment]
Some digging around leads me to believe the issue is related to the transform applied on the `div` holding the `svg` here
`web\src\components\Viewport\index.tsx:139`
and the transform being set here
`web\src\components\Viewport\index.tsx:71`

Still unable to test myself so any additional information would be greatly appreciated

**Comment by Wibbbs** [comment]
It’s working!! Thank so much for the quick work. However I noticed the new gem links feature isn’t showing.

**Comment by Wibbbs** [comment]
Scratch that. I had to reset and reimport the build then the gemlinks show successfully. Great work! Thanks all involved!
