### ISSUE TITLE
Feature Request: Copy Button for custom Edits

### ISSUE THREAD

**Issue by Xeratas** [HeartofPhos/exile-leveling#52]
When I edit the Route and add a custom line for example like this:
![image](https://user-images.githubusercontent.com/129869230/229813712-9436c5d2-60ae-4af5-9d92-3f7e6d072aab.png)
It would be cool to have a button that copys a predefined text. For example:

**Search Vendor for R-B-B {copy|'b-b-r|b-r-b|r-b-b'}**

![image](https://user-images.githubusercontent.com/129869230/229815122-37273af7-7645-4cfb-a70b-b29509bb02fc.png)

**Comment by HeartofPhos** [comment]
Added by c699980aa300fd69ee4d938438ae9bad6d4272f7
