### ISSUE TITLE
Add deterministic pathing for campaign maps

### ISSUE THREAD

**Issue by Relaxe-SS14** [HeartofPhos/exile-leveling#54]
The direction that a player needs to travel to avoid walls and dead ends is actually deterministically created by the server.
I believe this would fit well in your guide.

The below google document provides an outline, or description, for the fastest way to get to the next step in the leveling process graphically. 
 https://docs.google.com/document/d/1sExA-AnTbroJ-HN2neZiij5G4X9u2ENlC7m_zf1tqP8/edit#heading=h.zeohl0yvxvkf

**Comment by HeartofPhos** [comment]
I am aware of the google document you mentioned, unfortunately it doesn't cover all layouts so occasionally just adds confusion. Considering the maintenance cost for new areas (POE 2) I don't plan on committing to any solution that isn't data driven for this
