### ISSUE TITLE
Ranger gem reward(s) missing / wrong in act 1

### ISSUE THREAD

**Issue by Boregore** [HeartofPhos/exile-leveling#59]
I imported a Ranger PoB code to get the info about when and which gems to acquire and it seems there's an error with the Ranger. I haven't tested other classes so I can't say if this is the only one. 

This is the PoB I used: https://pobb.in/QI9RjimDy6V5

Here's what I experienced that I think is wrong:

1. Guide tells me to buy Pierce from Nessa after Hillock, but ranger gets Pierce from chest in strand. 
2. Guide doesn't tell me to buy or take Chance to Poison, even though it's part of PoB.
    * Guide also doesn't tell me to take Mirage Archer (same quest reward as Chance to Poison), instead it tells me to buy it. I figured it was supposed to tell me to take one of these gems and buy the other, but it only tells me to buy Mirage Archer.

~~This led to think ranger rewards have been replaced or swapped with shadow, but this is just guesswork from my side.~~ Nevermind this, just realised Shadow cannot buy Pierce support from Nessa.

Let me know if you need screenshots or anything else from me.

**Comment by HeartofPhos** [comment]
Currently I'm not tracking starter/chest gems which is why it behaves the way it does, but I do consider is a bug, will look into a solution for 3.21

**Comment by Boregore** [comment]
Oh I see. Makes sense.

Then there's the thing about Mirage Archer - telling me to buy it instead
of taking it from quest reward.

Btw it's not a problem for me for league start, I'm gonna edit some stuff
in the route anyway so I'll just add it manually. I just wanted to mention
it here in case it was a bug.

**Comment by Boregore** [comment]
Thanks, I'll try that.

Have a good one!

**Comment by Boregore** [comment]
Just realized I made a mistake about Chance to Poison. In the PoB I linked it comes from an item and not from the gem. Sorry about that.
