### ISSUE TITLE
enh: Keyboard events to toggle isCompleted

### ISSUE THREAD

**Issue by unixtreme** [HeartofPhos/exile-leveling#60]
The idea would be to capture keyboard events in the root container (body would be better but seems even trickier) that allow for example:

E -> `isCompleted` on whichever is the first `!isCompleted`  `TaskListItem` child encountered.
Q -> `!isCompleted` on the first `isCompleted` `TaskListItem` child encountered.

It's the first time I look at JS code for more than a minute so I'm not sure how feasible it would be to iterate all `RoutesContainer` and their children and toggle accordingly.

**Comment by HeartofPhos** [comment]
Plan on handling this while implementing #17
Worth investigating a nice way to have users learn which hotkeys are available in a given context
