### ISSUE TITLE
Where is North?

### ISSUE THREAD

**Issue by Rewind936** [HeartofPhos/exile-leveling#69]
Hi,
maybe its just me?  But where is North ?
Straight Up? Or Top right? or Top left?

**Comment by HeartofPhos** [comment]
I am unsure, ingame it felt too inconsistent to use cardinal directions for the route so instead I opted to use arrows 
![image](https://user-images.githubusercontent.com/43216176/234972432-6fba9adc-f0fe-429a-9aa5-6ec6696c1797.png)
Where Up = Straight Up, though many places where it's used in the route it's to give a best guess at the direction and might be incorrect for some layouts
