### ISSUE TITLE
Bug: Templar tries to get faster attacks when it isnt available

### ISSUE THREAD

**Issue by Copperearth** [HeartofPhos/exile-leveling#73]
Templar for some reason tries to get faster attacks support after "Sharp and Cruel" in Act 2. The earliest Templar can get faster attacks support is in library.

how to replicate: load a templar pob that uses faster attacks support

**Comment by HeartofPhos** [comment]
Fixed by b1a897bb05d7a39154779a99fbdd30f4a1ad9dc3
