### ISSUE TITLE
Importing build won't show gem checkpoints in Route unless you click "Gems only". But then it won't show waypoint, trials, and other meaningful info.

### ISSUE THREAD

**Issue by marcschool1** [HeartofPhos/exile-leveling#76]
I can't get the import build to show the step by step for gems on the route unless I click "Gems only", and if I do that it won't show me waypoints I need to take or trials I should complete at certain points in the campaign. It also won't export to the overlay in game.

**Comment by HeartofPhos** [comment]
That's a bug, fixed by cfbf33f8bab36c556be290515729852cc47b4ef1 you may need to force refresh

**Comment by marcschool1** [comment]
I've refreshed a ton of times it still will not merge the two.

**Comment by HeartofPhos** [comment]
I've just pushed the fix, should be fixed if you force refresh with Ctrl-F5

**Comment by marcschool1** [comment]
It's working now. Bless you and your quick response. 🙏
