### ISSUE TITLE
Add option back for one in all sidebar

### ISSUE THREAD

**Issue by Medivha** [HeartofPhos/exile-leveling#77]
Idk maybe I'm wrong but wasn't it before that tree gems and search was all on one thing. (in order tree->search->gems) Switching between the 3 is not necessary when it fits on one screen and I don't need to tab out all the time.

**Comment by Medivha** [comment]
Maybe 2 sidebars? Gems on left and search and tree on the right? idk i feel the tool should have the goal to reduce clicks, so you just can look at it and just play (and I understand that this is not the main goal of it ;) )

also the middle part is huge, idk if it needs to stretch so wide (but I guess mobile is a bit in mind)

**Comment by HeartofPhos** [comment]
That's vaguely what I want to implement, putting optionally each section side by side.

In an ideal world you could just put it on a 2nd screen and never need to tab out, but practically that's not happening anytime soon. I've considered making a client side binary that can communicate with the website for things like automatically marking sections as done, similar to how the https://github.com/Lailloken/Lailloken-UI integration works.

Unfortunately it's not possible to create a true "brain-off" experience, POB simply has too much freedom in naming/grouping things to assume some form of convention. Users simply have to click next/prev for passive trees and gemlinks.

**Comment by Medivha** [comment]
for now, I helped my self and created some custom filters for ublock origin and let it show all again and in reversed order so regex is on top

in My filters
```
! 2023-08-14 https://heartofphos.github.io
heartofphos.github.io##._hidden_yla8g_59:style(display: flex !important)
heartofphos.github.io##._contents_yla8g_41:style(flex-direction: column-reverse !important)
heartofphos.github.io##._searchStrings_1fdst_1:style(height: 40px !important)
```

**Comment by HeartofPhos** [comment]
8105280b5799e9b406766f2fb3fc51399d4f11d0 Adds back the option to show all sidebar items
![image](https://github.com/HeartofPhos/exile-leveling/assets/43216176/f9b10e9e-26f2-488a-adb2-7e1db8431ca8)
