### ISSUE TITLE
Feature Request: Add a "detailed" mode with layout tips

### ISSUE THREAD

**Issue by Mikaral** [HeartofPhos/exile-leveling#78]
Recently, I watched Locohol's [videos](https://youtube.com/playlist?list=PLIFjH3uOq6ZgUShmuy2WYcefkGtLZ9Rr_) about some patterns in layouts that help you get through the campaign much faster. 

I suggest a toggle option to allow users to switch between the current version, and this detailed version with these layout tricks that would significantly help those who don't know. Alternatively, the site could show these details when you hover your mouse on a step.

Thank you for your time!

**Comment by HeartofPhos** [comment]
See discussion here https://github.com/HeartofPhos/exile-leveling/pull/74#issuecomment-1663869972
Currently the route is already unpleasantly dense, some form of hint/detailed toggle per step would alleviate the current density as well as allowing in-depth information when users are interested

**Comment by HeartofPhos** [comment]
Partially resolved by #74 and the new sub step system
