### ISSUE TITLE
Duplicate Quest Reward but Different Gems

### ISSUE THREAD

**Issue by wizardofmaz** [HeartofPhos/exile-leveling#8]
Hello! Loving the tool so far.
I put in a test build and was going through "completing" rows when I noticed it told me to hand in "The Caged Brute" as both Item 29 and Item 36 and take different quest reward gems for Items 30 and 37. Other instances I've seen so far of multiple gems from a single quest turn-in correctly indicate to take one as a reward and purchase the other.

![image](https://user-images.githubusercontent.com/110843354/183464621-36857c8a-c7aa-4487-9b9a-21efb625941f.png)

The PoB I used is below, but again I did move/delete some gems.
Thanks!

eNrtXW1z2kqy_rz-FSpX7a1zK-BoRu-5yW6BsbFjY2OD3_LFJdAAMkLCkgDjU-e_354ZCQRGQsjOudm6OdlNQJrume7pfrp7Rhq-\_vtl5AhT4ge2537bRwfivkDcrmfZbv_b_k37uKzv__tfe1-bZji47FUntkPv_GvvH1_ZZ8EhU-J829eBLDT9PglvY1bSI1wbm244IJ7bMJ88v-5Z3_YvPJfsCx3Tteww_tZ1zCC4MEfk2_616faJvy-YQZe41mHyhm3RGyPTdlted0jCuu9NxjDkfWFqk1nDs6DVaaN5ed1O9Gu7yX5h3P_42nTMOfFboRkKAfz1bb8C4pt9UjNH8DdwM50JsJKwqCsHItYUSdT1_c-baVtjQqwFjXKgIYzT2jZ9ctTrkW5oT8mhb4eHA9PtJjpEB1iW04gLETQmTmiPHZsqLiKSDww1jeTkTRdIFNMat73QdGrN1rKtLmFNPRANGatIN7LpvHBBl9rDnR0Oqg7ot0AvlPa079ohKUjc9OzAc98hX5I0VcTDieOAP-Vr6406tltIGw3TNQ-9YKlzpKQ1Pbd7ZKVp6niOWvnaXYNX5WtJh9kkPnh-mI-ADnYngqiHFul6gC679LELSUKOYp0VoDxqFSEo0FErXIKJloo-1-Q52RApqQZXIy9LcBJxBsNkywyGp-5SCtXI4JdsmDnAqRdCSNuuGub6RyfNJVdJQ-hA1XRwU4S01MAwmAd213Qa5os9mowAhtvmkCw7VJGoHugo-oPTjac_CF2AkzQ-2MDigapgpEkGktLYHNs-SeWARXwgK4aIVMmQ0mOP51jvZTEwvSCNB1I140DSMkFs2aGqaxnhu_uFtj51u0vuWM1ifOP6JCD-NBH3s7qgJNfgXzTJ6DgkN82ym8hP8wRl3lk_aTvGga7irPbnhHQHdUirrs1wOTxF0g7kLIBbtpT1TPXSxkn1ZsLmBuWm-80qwbqapAMkYgiKmk7_zYyNqyozDtSsxpv1hcQMsjvTt3Igskv8_rw1sImzY-vIvuaH5jgHgNNJSVLnmpzV7pLqykWyWWnppFMzSEIukmQsZQvEKZKyYDmVpEEgrwQSi6wlvKqUnr17TzR3d3akq_gjb5IImRlxgAnC2yflSM_x48DBS5drYk26K5FKSbXIqgM11JoMWRbjODtRVMLQ7A5rntUnO3WyO0VrMh4DAtC5X6MzjKwId00CO5HulNPLtmXrS_CxXC5G41_-Dpatc3ewCPVrveg5CfJLQsPwuihqnua5u1jUxA3AsBEgOKupoZ5fOvKBhFJnByqoXOVT05vBgAZ0kSLYrTVkIcugkjoOn7iv83X-eq7myQ70dDS1Jj418NwyrFPkkqPCpgIyWTI6t0d2IuuIKNr2CMAzCGpmaAoBMf3u4Bym-9s-u__1M1sXop9OR2PPD9nFQ9PpBoz61B1PQsFlSzojO-g-dia9Hl272Yf-fbbodHR8fHTYPr09ijpMkgRD23Ee3cmoQ5c0-L_LobUIgz8hmHQC_vHb_q1NZi1KVSOhaTugtq7nOOY4INa3_Z7pBNCzDR9ZmxZI1g0zuLFWkI7Ga0WbeS0bpHM6eiF-CPJCatD1bZI6rsX9LYPiHdIsgE5QGje67pLOiKP2oRmEPEqnaIoteaVzoQtPqeLQmxm0YDOmk9pzdHeLJsL5mAQQSe2e3aWGnT3lbWjNW2XopdsFR-rOM-Y7ij3pPNhCVhoDfjOdmC9GpVFHdzO0yhbCUrXK76aT10jXTJWd30wnXiR-nntC0WQzl0WrDE4XnsuMHJymYjs0UKTO7JFDFk3SGV6GA-Lz6JPKqQEYFTfJdBzf7kzCdDdOtMjQFStbUzRE76WT8oosRQZ6LwOJVsqOFIUm26Sz4nVOKpBlkcZpcor6-N0MIeKCIWX80e10BjxpSZ2_KAXK8m9Ij9P9m95MJ-b-8ZZF6E9ycmC2XCM9AiiUacyLNhn-zkJJZerZFk-o38WNjWwzs6V4O_Hinr1R2J05soLjnRKu1yEfov5owSsFdBNNtjACtDzJiMf5OC1S9BNiOnRvxHPex_DNwt675PTCwHStGl2VyC3o189xUvqV5QGBEEC2WiejoDqHeuKYIt3ansvIDCFIQV5M9zzbHs2qzW5I_HO-Bxp1ZjJFRelkyPYnVzjHRmqRnjlx6PWrienY4Zxm8omrEVcMF4OBN6P2xdnQjCUASDw_53cqThhxoH3E4-DaikYhhHboEFp1eEEoVB3Ton5D1YJYw6gl21ytLMfPNMQksN2uM7HIqRuVWwtpHbNDR0k3jenq5sIFA8ejqwyeNRdiZF9jvuj7H19h3BF93fE6poOX7JdKSDZAi24op1MrkiwW7Jmr45SlJ0yfUcum6fMZ6ZMRvduAmsCCOubzKZQ7wWeqv89scPBpE0c2ReuSxoyX2up6E5f3Q6sWuqqzrnpG1LBdjh-T0cgDI2tCDhmawYib-sfoJTKb5sTthhNaX90Rc0whapOOsrSyML8LupLQoXJkqmWTDhKkHy8i2-umNeSQvEO6TVzyipekzZCPM9hVvOSCwaXbgrIdJhOM6pW4kJyN5u-QOTfrvIo47RKhuqgpCs5y1GBdDxXLIhZdMYtL8MJip3FalTIaxiYxGQOBchCS5f7HykvZN4lLQt_kS7uF5U3jlFteJmmSAxf3K4fMnxNHfmrQODFDnxblu6o0ihBr5Hm9IyLbihCJGLGmxdwCgjQ2zbqrpuvSBbN1ljw7WV6kQsZJy4cE0fUB7KiqmFzYIMAybl5DSCP-hzoflFueFYQmzf3Wxr6rlUDdmyl9hsMBaSz5Rwp3QnzTsS57p13yQdO8iWNuKTmx4PWE024eCC3iF2kqaEJOFM5THONdqlnvobhWNowRYs-LHRwBQ9ICULaJH3fH9nmylOjazk4AAvXNyHYLxp4FCmzikh8EktT_6THnbmD79JG_rFolD6psZpNXpzH5_1lBcmwGMKt8w-E9qesmNnmVwIkFTh3kFxLlFhL-b_felZqvccgtWkSXtwzZLhLbEWSPTRS2WUbN-OwsT4WumUHa6QhNHxh0Q8_PZ7P_uUBxNbGjJyiK464ZDHaHW0r08Q4PxZJNAdx0Dj0IWd7sPaUMf171znZ3z745qcBofzUT2XFlgC0pddjO3s_M4RPd7IpCGwf4UxP3ShCYQWC7QcP0h4Udh-5S0-eq7og5dEkQFFgbiMbxX-bYC_4nENhw_tMhiS-JeqPOhy6xJvntZFkCJ_15qcu6cd2ZkC-0xgPif1jhNLdAklWO-UuEBPHHm1Y5_i-PjX3e3iUrPN52yuuRvNZMW39UbQPV5qGfjJDvm8o37HZZLeWUH1a2_WL5Z26z_JttRNumR7YM1DJdqxXyzeufGWdZZxWX9bezwhmxAJQCJ98ebxOTEn0EadjGKN8PpR_bPiHxhibrRo72FeFLvKd46Jizlfc1T9m2IswLra7m0cMz3_b_xKImiSUZi0j-q_SnLCPNKCEJqxp8Q4aoiCWMRUWFbxJChlaSZV01_gIhPYvud2JFQajE3qMpYUnWUElRVVktIVlUShhpil7CiqhqJUWSMTQEcqkkqRg-q0gS1ZIiSpIO11XoFsm8A8RaKCVVxqpSkjQVGSWsaboOzLFRkkRNBuaKrKglGemqWpIUXUEl2TBEEEWXgSGIIdK_4U-JvlsDYhgSiKZKSAJmGAMVF0-SkAHD0EUMF3QYr6oZ0I6-vAd9aJpSQqougxiaCv0psmbA8BRJl4FGxjBeDXosGZjKAqOD5rIuwk1RVmCokgpDjTSn66IGA4DxwWfRoHeRXEK6BF1zxWMZSRKwQSCSoSHQC0gHw9Aw1ZqsalQDim6UFIOJLYsicEHQSUkGNYJSZFnCMEiQXabDxTo0B1466BuGq0E7BIMBSizTaaY96yqMApqB6mS4T1kAH1VGJdA-pvOHVbGkYAx2AuozgFDhJHTidAl0o4IRKTDFMINwxQAlKDqmtiAj0CIMEIFakApzBFNODUxW6UfdoOPWdA04gi5BKhW0qIqKQT9jmF0Vpr0UmaihqCA-NkC5MHNgL1gxJGlfCMEdEu83Iz16dZlaPI420m-uzzn4DMJwHHz5_Hk2mx2MzXDg9ciL7ZCDrjf6PKa54ZSUmZeWKdvPFfiv2j-tduqXbu_-tuMbqF69RzePoxNfPMP1QIaZlfwjr48vzi-H1_0HXC3PRi0dzxvHPSTX7y5mnvzcONTPg2n7x7Fx1Gg_-uP57NF8up2Oz0yvHhw_jy-Gg-em1leGvnhy1ak83VVlT57cz56McOpeWq1a5961ps895UGbPtWa3096z_P2_fDmVv8ejJzZj-ehbGHpShpjr_2DeAAEt8bsuFVpNeqP85EsDc3nw17trvI69KVRvXNVnZ7dnz8cHbte_Sx4rXQwfnot1x-eb18vxcdX6fnhpnzZEyVFvZnjmmV0j8N7e_I8Cwx58nSnnVfuv_vt45umX_UaqtdykdO-qhzd2oMz89k4Jpb4Kqrz9riqXJX7375xWItn4Ct_TTyIYgH_xtCEzhfDBwg2IQdmJC6i71pDZnEbGgJOLvnDF4DEN9hYM_vrb7MXQcefiYcRkiwBMQmFioaMGBCxKAK2IQ1GGKEg9xAOMBEWMvxKYiFz3QgKoVM1RiUGoFwu7sAcETn0RZDIYDSCXYZuHEy5k7-BxMi9E5DIVcoQgCOiooIMHLMSgKhgSYvxkMOCxgSiyBPhIQfuBB5yGEriIUI6dMlhiAEixAxlBQ85qka4xgCRox4Hs3VE5IjLUTVCxCVaMVDlgYTBGaiR2gLHQ4rpGMtYigMXsyUOhxy1IzxkkAczoaEI_cEuQKdxPKBwq4A1xUjO0fnXA0QALgaIveD7cNrsdQAQ2_a41niYnb8-25qsifjKqtaOHlW1_uBjD3lm-a55qJ24FljJxXA0OwVAnM_Uy7M-Rndld9xmgPgcnF9a1wAsdwgA0Zxd3_QZIA6u0f3w3kMApFNCAbEeMECciI8MEFtKW5TkVqN6cssA0bOwEXqvwxHpv0peBIj1I3z3OAdADIJqdwSAeff8JNntZvnh5uV-dqtYT92zedsyrF73xJ6EjftaQ-nWNbnc-T6-b8wb876Lz4IIEGu-eKtI5hW5aXoMEHcBwjR8y42Y-YEQF0BCTZXADUUFKX9zYshxkBt9hICpeSBFQB1QKBUGkykhxzsOsJKuA4JEOMjAh-NgnOxQHOTYx3OgRKrGgZvDIIcJBoMM7lYTQwpe3IWTieE6DHIoTeSFDAY5aHEYZIDD0jcOghx7kiDIEYjnXzwrZAiXRMEodVtmhdAXBUdVNt6mhdBUNyIo5CDIAwR7DZ4CG9gGB1QGizQ-QD8UhONEkeExsyEeNlJhUJMxjiIaB1oeT3jIiUyShQQeBn7dvBBg8OH5JXiqL_PBSblh4_MlDHaDJvYg7xpOL-9FgEH14sfFEGBF66u1zvXobDQ376sAq53H0ycD4A_ywqp_dthjeeFLBIO-o7O8sPrcHEgAgy_mc73THmOAMQaDPwbt84cG5IWkz2AwMFSWF4bh5MmLYfAokB_aP14rP4LDo27dr0N-OOiObqf3DxbAKcCoJQIcL2HwTmkGqqedH_qHqKPeNJ8NJRQvVmDwtvJ0Yp0NT5ya-svlg3cDION7DwVyQqyAa6oyFIqZGSK9J4H_yhpAWGGYfJsjgi_RjIuNInemyDxkBS2jJIwmXXnQkmeNkqqJsavGsjL5OVoyiONoGeUwzNmj4lvXRCly5zdZY5TUJLNGhg0MbjPraI65b-pojuKbAZPPCwdMBlg8aYzwhgEbT-QYXka5MIO3BF5GaLieNPJUkmEkx2XZkBc5J8dCnr9S2I9qZkmk41tmuxwtscGmjEWgN0U0jz08aYwKfBaeeFSEESpRzsihNErBGVjCwCX0N4Hl3SawlKYkaNm43Gt31Afn6OFEO_xx_iphI3g6kp-vXo-dNuSMs8kr5HrXCIroqpgoou8g33s4b0PRiYOhiFt983VSm5SbxLm4Kw-HzefZROkdNvHD80xBx8YMitzy-NF5AvBt6EOr3Hn8Tq6v72ejecdDo-f28bP3I7x0Tf_6RR1ADnjuNCEXPJ1BDth5upudQs548VC7bA0u3Cbp1_VxN3S9xqzeJKftm1MLa-1HqwY5qaw8Ng9ZLtpp99x26HRfJDS7Q-RMva8GjVfve7nWMS_Pqi3p9BWK6Jvm-Kz30J5WKvdGFfTAQLPdbPvfL9X6s9gtUkznziEZhvzsZDP5qH2553t0FXsyyoW4UCtICVAVKQAZuraGqevrlVBiAKiIkvgWijF4tgoohxJAzKtYBsTg0QpNdkRAi4gL9B67IwNivjIYwTFPHVUMUMYzWHBYih3cExNLmRysuT8yaOaLWom1TQADmg2zFU6-zKYrMk2nVBiKArBdAsG1yLExYJ4SYSv3bBjKoowHcEMRjHOITtT-kkKRkKM4wBwW48VQpiYElhOjOAdems2IUcSBsGFQDGG1-5vlUA7AsqEusDIJ4yqMWGZApfMQJ8Ew6WxiDuIcQBVNlo0IlxPFP4XA5VIhLbhBFXhD7c_DmAiYrRsslGEkRSvCHMRZkElgOEdrmBZFiZYJQOcI6xASDQmuwcwqMg3ECuVGJ4SZpKLr9DJfJZUMurzJ12g1UA7Qw2wDO13HEYYbtJjh9vsGwpEI-XAcLRVFjCsMvp6gA1EE4Tw2gg0u1kFBcdrfBOHkuKMChBsXt3L7aHTZfTmXRuIZGvplAwZbvphC3nthtPquTNdB3XZndhNK-LHq1el6qDQ6u-__aDblwUP1qRMMhiMHIPD2Zjp90lXv2H881L5P0JV1KL706LLA83cReaaCrs9M17WagXExdIxZ-_q8o8gzfHPTY-ukncfzKgJovrTaL3bQUKv3-Ojl6mhYa543yaQ69q9f2bKA1TwyZMhjHakdLQtc3VhXZf904j3e3tyLI1l8MqYds3Z36Mwl3T96qlSntdPq99NwdjM6sa_OKp1O-X70Q61aT3S9ddqf9c67NuTDw8f74WO8TnrWn05q00fSx-Ld89CU5o0X2z-7liEfVrVZ5cS9b7Qe0IPXGj1Pr-9dqyyJ1e_nHoSc2av4Ek4P1VBpzv7mddO3Damn5ob6r5_pphT9cOGFhN2jF-MvbMuKnvkQHU3RCn26Z_jqeaOHb_tlZNCzx5ACJaduUFOmL9CdEDNsmOPFBjhtHL19J0cv34VmWLMhSvjs5c14I442vAeu4OoHCgbXAATXo5OmvrIdvmjzbLFXiPeFSUCix5fYm1jscuKVPdpUmJq-bdI9PmnlLb1rkz4J_EW4uTi9ujnau_Tp_p8b0oeEwwERjiCa7dUnoXBtj8fE37vlXL4ITZ8I-EA9EFcvSQdi8tLhxAfxwj1-CAaxhMUdKck1etfwi4DFvWiCvgj1MvzZY0q7Js9fBFndOx2NHbtr07t4789Ioi_or08YCfRldqHPnq4Xep4vELM7ENi7RgJUSEJnHj-UuSQElPrrkyzvQPoJCaEnsDFRDfGxAlWNvEDQBxEEuv267EH6a9GkzqYOVBTthMMlYMx2jQUkCqsPjiaEK-G__vTpCbZfxAPlrz-QKJYRFv_7n3RP2ydmAHziI5uiV4aS3a-QqkCqbyFd6aqMlJXWfHQCO61jDyvJW61w4grxmWF79PVgoWtGjyqBCsGS6AlXFnPChmexM3kF1tm3feiN26QSu2lqC3Vri_gkLLYdvsH8MW-GN5p_xXEmPgH7BY3QTeiCxo0THDbadrUMfxK2ra7YNtrD_2RP6ceTE-mdz5HADraA7syAWW7SEZLTp8P0iTkNZc3G6MxLuQ2lYlmB8AdSymCW1D3-kMSyDB-zbEsHI043LbRiWvEZTvymMBtAqAfmZmC7_aTwD96EeXF8j_myBKBNkTEQPBdwkl42BTY77JGEpAo20oNrZjPINEa81VylrS3krS2ULSYvxV1tMvnTV9P34kcKa6Da0cikxghwttEJNoK-lhf0Vxnnwn1Vz8B9pTjuq7uQJkxXFstqtm8wh8Ai9QVFfA_EpkWBT39ANl-WFO5v8VFCwrUZrriEtEojidQvN9MAUmRIFPkcf3_3vfb8N4K8vNHi294E5hnwteL2J3Yw2MHasyD_1zDt4obNYRysOzKrPyAEgHVuAHJpxVYSLyuv2DaPAisto0egIVmgL7QL_ICrPQzsuuwj7ZYhsCnwF8gF_gY5hd4zmx1rzm5RM-Ty7EUHbUA7Sgb_W7wTIIT2KLZcMxRG_HiQVcYBGH6yc7hJXsne2kADwfKgtAgF05mZ8yBu9TF-sG7D_NYmu617HYdOKUWYUWcSDCBzPidmf0K-QCIdgsHltDpxNdlYnU7-3GLaXCUnGAOeAA7lzicxbZ4KdoLdE-YQgQfmlCzyxsiG180B8kzwQme-wh6yWz2PvWV3xA5pzOrn0zKjAIOpTfh76xROojHSByaTXFjiEB3KH41kjx7OBA6GIwdj_praSmSJFT1xa0ObXzf94Ei-Mcv2zSEkUHacdRwDw71jm7gUR-imfr6kWZFW7VjewY5ZvFv6fdu3ab9RZYcgKtoBVGpj-vsgQYw-q5Fbo9OyY44MWa_EsRVmXtqArKwZqzEVQ2AHn8Z3aEq8HC8_no8ODCqtD5rhbemjtnEul9uPywDYGhLTXU8REXqbNiJ157yR8y5UVBXEuai8ocWzEUVGDLWVRJ0yLfblzuvSM7ToeLk3SR1NXleIwJQZjGSTvVlHUDgYL20qPm1MYGePrWZ-gJe-cNnrCScU3exAIKNxOE9baIgj_8fwRn-tJacJpedksaYztoiy7ry5uf46iPsRKXRGCyMfLugbcaFm-kPfnAu37MXaYK_mm33PDcDTiFD1vDDY42d4gQvLUvS5ChMRnbgP-v8iiAeGgdFeZNK8ZfQlpen2SjU_5LwdcXp2tZpfKUncEdPNEHJtbdUIuR5YChEJurda9kWeRRch49O3BX6OJIOtrHUTANDVNCpazWxsSoyT7qeA9_n0HHhgspqHxdnPqojy9vZ07TBuwgQBvLLsydq6J94OIW-FSmASWoGNVWTcQJnpDGiru-B87mJsrkkHNIhCznFpDveqdjCahAPh2DGDYeYSZGTTSl6bXuWctOel-eop1ktnpMbOe-PkAt_iLgkoMd_RtIT0TESaE_PK0-F2SEtRgFa4wqD1xu2a4zGdGX4fgvDSlCneOpBFB2FyRjf2r_5N3aPN3Ud9xodYEbr0888kq_eOYwAOsjKQlUiec0yLlORnDkwqMjClrP-cYX1MCN1U1iBxoxMfMySjw21N_Kk9hYL81vZtC3QjfCcz4uxxlPsiNAj8O9pjp-GDJKEXLSAl3C4zm0zmnfSX5egChwO3QkEWE5tRthvhaklgB2XEJBY9cpUuAyUfa0lOCq02WB-J2JKvnxWOAxOcYSUmLX_xJEqF84DutmU-tHkvsxVCDuK5T2ZcZ54Q09pr2Q4FhxPPs5aZhW4oWZmFohVeFUx2lzd_EFdNQXmLr7MBYdXfuTdb2wPasFu4tpOTWiGs1yLxQuBinlN6-fSHwhKZ1barwTdj5zB3IfYp3tKiHcXLees7YMqmIm8t9GdpDxVi8AvUBFq-9ANt3vism_5kODAXZ0scOxTLwIXY4cxR_rtwF4RQZiauq-spivKeTHx1FHm9KB1QP8U7lJuN--02Ks7nQau-J9E1Hj0f5Xr9DJRyJuXqWsZqpg9yjyYuS5qrE5-VCPR3bV2rJLQGVGFW9J3VGYdQ6zqLS3vsd7gIjQKQ14l8ZZKmynzNM6qMR950DTpWS4kFFRI3ogfdf8PbCT4mIf8Za2NsAGv7qdeV66O9ymjikHDv3BxDIhJ9OfTNHlj0F4E-4bMHxt-zX74I9MeDM760Jr08XxKroauLXetlo8TN_dQNoXqy-_SZo0Kxl91a21drVOqnh3s12xxRE-G1RYbQKwJsrkGwtuq8K-NoOV782z38eScBLR_1imEw0eiEOCMSJp4GQ2_b8Cw1wcdIa4MTjOS3jRhGLZvob1twq0hwiX83KXqiK-NprtXzEVbOWn-rk9bMHAuVzjwIaFDlz8clHp5bPBK3gXSdDOcjW7aSN7Rimik4oE2ybBlUlUCKuxsJn2Ap15DwpiFJxdSbTwn4g8jkYoNUi_WmFtcm2jLBm-xpywxwKNi1ow2WpBbpZ4v5Qa45JUERxlJxL0JF-pOL2QIqZnny9unJo9hd2W4yr4KC58IdpcB4CmCgtK2bxc9r7Dh9m7VcyL6UIkS5XDLPRLzNAnLIqRRWKy4w72oxT5KKma-0u5XJxWG_gE2jwsqX8hiEnKdRgWG_I_nJOZPZGVnWLKgFrLL4NLzDXPJCMqXN6TX5mxbQ3DWtx3ERKMWF1VsQLvLPZxFxpBx6QsWnQS6sLaWINHn85U1ZmNvItwxpvaQUk7U7P4Jvl_IyeaRA4l2JX63I1H4Xmb-LzN9F5u8i83eR-bvI_DWLTIR-V5m_q8yfU2Ui-RcsM8XfZebvMvN3mfn_o8xc7Fwm6kz-mR2bcei5PbvPa093PIm5dCa93pEzoYe07Asdz3OI6UanX3x-0xiK1eRPyQbbKWhly94ApEf90-cKtpMQ-ibhaVD16K-y0B_bdftUlUGwoW3HpOyXzegm9oZmY9MNB8RzG7br-XXPyk9gPuUjWMjJjgOAltvlpJqP3m3f3LjpmF0y8ByL-EnVsKdK9gV3MuoQH-puUcxuz15c4k8OLqmwkk20eJ49_uncmBAhcQspfXSMPy62pNpCcmz7ZH2E8jaxEr_rm39wtKfdqdijEEsCXdqugfVOpDyztE6ENfVg20xRPeyqu_hFtwKaiO0ipcuvn2Oc-fq5aYaDy151YjsWEPxr738BMPQ9gw==

**Comment by HeartofPhos** [comment]
This is actually intentional, The Caged Brute has 2 separate rewards, one that's available when you reach The Lower Prison and one when you kill Brutus, I could have the guide suggest getting both rewards after Brutus, but flat damage support gems making killing him way less painful.

The wording can use some work though, so I've deployed an update to add Part 1/2 e.g.
![image](https://user-images.githubusercontent.com/43216176/183501720-e66184b2-3fe0-44ce-9ccb-cad3addd68fa.png)
which should hopefully make it less ambiguous

**Comment by wizardofmaz** [comment]
Hey thanks for the info! Been playing this game for at least 6 years and had no idea that was a two-part quest. There's always something new to learn in PoE haha.
Cheers!
