### ISSUE TITLE
Feature Request : Add the ability to add notes on desired section

### ISSUE THREAD

**Issue by Invidia2x** [HeartofPhos/exile-leveling#81]
The use case I encounter for this is for example act 1 muling which I don't think is possible right now, or stating which gem that needs to leveled up off-hand or just to offer some note like if there is another gem worth considering. Just a consideration for further improvement of the leveling experience if you like to be extra-prepared

**Comment by HeartofPhos** [comment]
Adding generic support for muling is a bit difficult but not impossible, in the meantime https://heartofphos.github.io/exile-leveling/#/edit-route can be used to freely add steps/notes to your route.

**Comment by Invidia2x** [comment]
Oh yeah, i really didn't think to use edit route to give some notes. I guess its just me issue then xD I hope you have a beautiful day and cheers!
