### ISSUE TITLE
Search only shows single string when using # 

### ISSUE THREAD

**Issue by gorsech** [HeartofPhos/exile-leveling#85]
Looks like a new bug surfaced with the search string. Could be related to https://github.com/HeartofPhos/exile-leveling/pull/80

Adding the `#` character to a string will only show that string in the search sidebar.

Missing a string:

![CleanShot 2023-08-15 at 11 29 02](https://github.com/HeartofPhos/exile-leveling/assets/28898416/33423250-f11d-45af-9412-a46c75be9a5f)

![CleanShot 2023-08-15 at 11 29 08](https://github.com/HeartofPhos/exile-leveling/assets/28898416/89cf69ab-7cad-4b67-a17c-c9ea1afae5ee)

Both strings visible as expected:

![CleanShot 2023-08-15 at 11 39 09](https://github.com/HeartofPhos/exile-leveling/assets/28898416/a4ab39b3-21d0-4624-92f8-6f0a6a2f7f92)

![CleanShot 2023-08-15 at 11 39 14](https://github.com/HeartofPhos/exile-leveling/assets/28898416/9e694eea-bea5-4702-9372-10c496181b81)

**Comment by HeartofPhos** [comment]
I reworked it a bit to be something more like "friendly name" as opposed "label" so in your first example clicking `bbb|bbg` would instead copy `nne|rint` to clipboard though in a more realistic scenario you'd likely do something like
```
#click for boots regex
nne|rint
```
to get 
![image](https://github.com/HeartofPhos/exile-leveling/assets/43216176/ca2a3e63-94ae-4f0d-beca-b04b6a0b1991)

**Comment by gorsech** [comment]
Ohh I see now, thanks for the clarification! That admittedly was not what I originally intended 😅 but this is honestly way better. Will close this one as done.
