### ISSUE TITLE
Gem only shows gems used in multiple links once

### ISSUE THREAD

**Issue by dyfrgi** [HeartofPhos/exile-leveling#87]
If a build uses gems in multiple links, I need to get multiple copies of that gem. However, the build import only shows one. e.g. if I have two skills defined:
Fireball - Controlled Destruction
Freezing Pulse - Controlled Destruction

and then import that, then when I'm able to get Controlled Destruction, I'm only told to get one of them.
![image](https://github.com/HeartofPhos/exile-leveling/assets/1012426/e9ae80c5-cc29-4e05-84ae-9eb480ad566e)
![image](https://github.com/HeartofPhos/exile-leveling/assets/1012426/f94cd1ee-93c1-46ef-a8c0-b73d1ea18dca)

Here's a near-minimal reproducer POB. https://pobb.in/PnuYjrw3RjZL

**Comment by HeartofPhos** [comment]
That is unfortunatelty intended, most build guides will have several repetions of gems for each act etc, so I opted to simplify that by only tracking one of each gem.

The most practical solution is probably to add an optional counter users can increment per gem on the build page

**Comment by dyfrgi** [comment]
An optional counter would work great, and is what I looked for first when I noticed the issue.

**Comment by t0nyandre** [comment]
I noticed the same thing as well and an optional counter would be an awesome implementation!

**Comment by HeartofPhos** [comment]
Added with da9aa3fa51c4e17bd81d28ba641815984c20d0fa
![image](https://github.com/HeartofPhos/exile-leveling/assets/43216176/8166903f-acfb-48f3-8419-7c89fdd00110)
![image](https://github.com/HeartofPhos/exile-leveling/assets/43216176/433d5bc0-06b2-4f74-a8d2-aa91332eaf65)
