### ISSUE TITLE
Hint for The Chamber of Innocence

### ISSUE THREAD

**Issue by Nightblade** [HeartofPhos/exile-leveling#89]
`Loop around clockwise`

should be
`Loop around anti-clockwise`  or `Loop around counter-clockwise`

**Comment by HeartofPhos** [comment]
This is intended but the UI is a bit unintuitive about it
![image](https://github.com/HeartofPhos/exile-leveling/assets/43216176/e03a677f-6200-4fa6-a68f-e3a2238a8b66)
> Loop around clockwise

refers to reaching the chamber of innocence entrance from the templar courts
> counter-clockwise spiral

refers to the route inside chamber of innocence to reach the boss

The route is consistent in the regards with hints being about how to complete the current step, but it reads a bit awkwardly
