### ISSUE TITLE
Data seeding don't work

### ISSUE THREAD

**Issue by roman-mukhlygin** [HeartofPhos/exile-leveling#90]
I used the exile-export project and got all the .dat64.json files, put them in the project folder. On the step
> `npm run seed data -w seeding`

I'm getting an error
```
function getGemCost(required_level: number) {
           ^
TypeError: Cannot read properties of undefined (reading 'Attribute')
    at D:\Programming\Sandbox\exile-leveling\seeding\src\seeding\gems.ts:35:58
    at Generator.next (<anonymous>)
    at D:\Programming\Sandbox\exile-leveling\seeding\src\seeding\gems.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Programming\Sandbox\exile-leveling\seeding\src\seeding\gems.ts:4:12)
    at getGems (D:\Programming\Sandbox\exile-leveling\seeding\src\seeding\gems.ts:32:12)
    at D:\Programming\Sandbox\exile-leveling\seeding\src\index.ts:23:70
    at Generator.next (<anonymous>)
    at D:\Programming\Sandbox\exile-leveling\seeding\src\index.ts:8:71
    at new Promise (<anonymous>)
npm ERR! Lifecycle script `seed` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: seeding@1.0.0
npm ERR!   at location: D:\Programming\Sandbox\exile-leveling\seeding
```
The source of the error is here gems.ts function getGems()
`const grantedEffects = Dat.GrantedEffects.data[skillGem.GrantedEffectsKey];`
grantedEffects is null or undefined because the skillGem object does not have a GrantedEffectsKey field. How can I fix it?
SkillGems.dat64.json it does not contain this field either
![image](https://github.com/HeartofPhos/exile-leveling/assets/60079597/40afbf72-4870-49a7-8db6-e294cc2f594a)

**Comment by HeartofPhos** [comment]
Fixed by https://github.com/HeartofPhos/exile-leveling/commit/867f4b933262ea932a4448558483685ca382b676 & https://github.com/HeartofPhos/exile-export/commit/87c2f96be1dc6da5d9e8a3f1beaf6977ddd9fee3
