### ISSUE TITLE
Mistake in the route of passage Act 3

### ISSUE THREAD

**Issue by roman-mukhlygin** [HeartofPhos/exile-leveling#91]
https://github.com/HeartofPhos/exile-leveling/blob/867f4b933262ea932a4448558483685ca382b676/common/data/routes/act-3.txt#L52C65-L52C65

> Hand in {quest|a3q5} #Fiery Dust, take {quest_text|Infernal Talc}

Step after "#Fiery Dust" don't display in web app. Perhaps this is a mistake.
![image](https://github.com/HeartofPhos/exile-leveling/assets/60079597/347af19b-fa93-4fdf-b4a8-d5ba09547264)

**Comment by HeartofPhos** [comment]
Fixed by eb7d69f54e1f0da7b60bc34162489f3ac4734371 now reads
![image](https://github.com/HeartofPhos/exile-leveling/assets/43216176/5fd65881-5876-4598-8c80-4560540b040b)
