### ISSUE TITLE
3.24 Trees from PoB 2.40.1 aren't displayed 

### ISSUE THREAD

**Issue by B-Souty** [HeartofPhos/exile-leveling#95]
After updating PoB to 2.40.1 and converting or creating Trees for the 3.24 league, they are not displayed on the website.

[Example pob](https://pobb.in/LAtbAyyI7sp9)

edit: some more added details. The import complete successfully and the gems are actually shown correctly. The issue only affects the trees.

**Comment by B-Souty** [comment]
Adding the new passive tree from [skilltree-export](https://github.com/grindinggear/skilltree-export/tree/7b58dcb9b93b1852e57ed81b1bf078aed137d384) to the `PASSIVE_TREE_JSON` [const](https://github.com/HeartofPhos/exile-leveling/blob/21e10e6502f657b7d6e1cf87f786bad93b0f1eaa/seeding/src/build-tree/index.ts#L5-L18) and running the passive tree seeder seem to fix the issue locally. However, the commit on skilltree-export indicate `3.24.0 preview` so I don't know if you want to include it before release.

**Comment by HeartofPhos** [comment]
Fixed by b731f06a227a5ed73bd629991e868937737fdba0

Might as well add it now, will just update it once the final export is out
