### ISSUE TITLE
Movement Speed - Rank 1 Crafting Recipe location is incorrect as of the 3.24 update

### ISSUE THREAD

**Issue by xuvvy** [HeartofPhos/exile-leveling#97]
`Movement Speed - Rank 1 Crafting Recipe` location needs to be moved in accordance with the 3.24 patch notes:

> Added a myriad of small improvements and surprises to the Campaign. Fun encounters and secrets have been scattered throughout Wraeclast, though the fundamentals of the Campaign are still intact. On an totally unrelated note, **the Crafting Recipe unlock for Movement Speed - Rank 1 can now be found in The City of Sarn**.

So, from Pyramid Apex to The City of Sarn (right at the location entrance).

**Comment by HeartofPhos** [comment]
Fixed by 40bea88468c9d06932c353e8cc2ab03c6ed09cb9
