### ISSUE TITLE
Act 1 Step 52-55

### ISSUE THREAD

**Issue by TheSofas** [HeartofPhos/exile-leveling#98]
In 3.24 GGG have made the exit to The Ship Graveyard behind the Allflame NPC teleport you directly next to Fairgraves. Changing the steps to enter the portal instead will save players some time not having to relog and then waypoint back to The Ship Graveyard.

**Comment by HeartofPhos** [comment]
Great suggestion, fixed by 4346614be263fbb832f36da0d0a1f11479addd0d
