### ISSUE TITLE
[Question/Feature] Template POB

### ISSUE THREAD

**Issue by jrock2004** [HeartofPhos/exile-leveling#99]
Really cool tool, I have tried importing a [POB](https://pobb.in/bWxeab5oqZ4u) and the build page is out of wack. Would be nice to know how authors can set up a POB that would work with your tool. If one exists and I missed it, sorry

**Comment by HeartofPhos** [comment]
Could you elaborate one what seems to be broken? I imported your POB and it seems to work as expected (gems are properly assigned by quest, passive point trees all work), the build page should generally "work" by default (sometimes nice to delete late game gems for some clarity for example)

**Comment by jrock2004** [comment]
Thanks for the response. If you look at the pob notes, the first question reward you select rolling magma but I do not see that. I see it taking raising zombie. I do not think the issue is on your end per-say. I think your importer is expecting skill/tree sets to be broken in a certain way. I just do not know what the tool expects

![image](https://github.com/HeartofPhos/exile-leveling/assets/655716/c7dafc9f-8dce-42b0-848a-78cdec21e4d2)

![image](https://github.com/HeartofPhos/exile-leveling/assets/655716/456b816d-4c5c-49e2-9ce8-7c6c3252e2dc)

**Comment by HeartofPhos** [comment]
Ah yeah, Rolling Magma isn't in the skill set/list so it's completely ignored, my goal is for the tool to always "work" assuming you have skills + passive tree setup, I have considered some form of "if you add x/y/z to your notes I'll interpret it and do a/b/c" but in the end I decided I can never replace the notes section in POB

My current recommendation for mules is manually update the route with (Edit Route)[https://heartofphos.github.io/exile-leveling/#/edit-route]
